# yaml-language-server: $schema=../vendor/symfony/routing/Loader/schema/routing.schema.json

# This file is the entry point to configure the routes of your app.
# Methods with the #[Route] attribute are automatically imported.
# See also https://symfony.com/doc/current/routing.html

# To list all registered routes, run the following command:
#   bin/console debug:router

controllers:
    resource: routing.controllers


accueil:
  path: /
  controller: App\Controller\HomeController::index

admin_infos:
    path: /admin/infos
    controller: App\Controller\Admin\AdminController::infos
    methods: GET|POST

admin_guide:
    path: /admin/guide
    controller: App\Controller\Admin\AdminController::guide
    methods: GET|POST

admin_home:
    path: /admin/
    controller: App\Controller\Admin\AdminController::admin_home
    methods: GET|POST

app_login:
    path: /login/
    controller: App\Controller\SecurityController::login
    methods: GET|POST

app_logout:
    path: /logout/
    controller: App\Controller\SecurityController::logout
    methods: GET|POST

utilisateurs:
    path: /admin/utilisateurs
    controller: App\Controller\Admin\AdminController::utilisateurs
    methods: GET|POST

utilisateurs_new:
    path: /admin/utilisateurs_new
    controller: App\Controller\Admin\AdminController::utilisateurs_new
    methods: GET|POST

utilisateurs_edit:
    path: /admin/utlisateurs_edit{id}
    controller: App\Controller\Admin\AdminController::utilisateurs_edit
    methods: GET|POST

utilisateurs_delete:
    path: /admin/utlisateurs_delete{id}
    controller: App\Controller\Admin\AdminController::utilisateurs_delete
    methods: GET|POST|DELETE